name = "lumi"
pages_build_output_dir = "frontend/dist"
compatibility_date = "2024-04-03"

# Cloudflare Pages KV bindings are managed in the Dashboard.
# Please bind a KV namespace to the variable "LUMI_KV".
